[package]
name = "dotfile_loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miette = "5.10.0"
nom = "7.1.3"
tokio = "1.29.1"
watchexec = "2.3.0"
watchexec-signals = "1.0.0"
